version: "3"
services:
  web:
    container_name: molitvabg-prod
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    expose:
      - 889
    networks:
      - molitvabg-prod
    ports:
      - "0.0.0.0:889:80"
    links:
      - api
  admin:
    container_name: admin.molitvabg-prod
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    expose:
      - 888
    networks:
      - molitvabg-prod
    ports:
      - "0.0.0.0:888:80"

  api:
    container_name: api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    expose:
      - 8081
    ports:
      - "8081:8081"
    volumes:
      - ./api:/home/node/app/
      - /home/node/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: production
    networks:
      - molitvabg-prod
    links:
      - mongodb

  mongodb:
    container_name: mongodb-prod
    image: mongo:4.2.0
    volumes:
      - ./data/:/data/
      - ./backup:/data/backup
    entrypoint:
      - mongod
    expose:
      - 27019
    ports:
      - "27019:27017"
    networks:
      - molitvabg-prod

    command: --bind_ip_all
networks:
  molitvabg-prod:
    driver: bridge
