version: "3"
services:
  web:
    container_name: molitvabg
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    expose:
      - 889
    networks:
      - molitvabg
    ports:
      - "0.0.0.0:889:80"
    links:
      - api
  admin:
    container_name: admin.molitvabg
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    expose:
      - 888
    networks:
      - molitvabg
    ports:
      - "0.0.0.0:888:80"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./api:/home/node/app/
      - /home/node/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      env_file: .env
      NODE_ENV: prodaction
    networks:
      - molitvabg
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:4.2.0
    volumes:
      - ./data/db:/data/db
      - ./backup:/data/backup
    entrypoint:
      - mongod
    expose:
      - 27018
    ports:
      - "27018:27017"
    networks:
      - molitvabg

    command: --bind_ip_all
networks:
  molitvabg:
    driver: bridge
